#ifndef BROWSERCLIENT_H
#define BROWSERCLIENT_H

namespace StaticPage {
    //The sign-in page
    const char loginPage[] PROGMEM = "<!DOCTYPE html>\n"
    "<html lang=\"en\">\n"
    "<head>\n"
    "<meta charset=\"UTF-8\">\n"
    "<meta name=\"viewport\" content=\"width=device-width, initial-scale=1.0\">\n"
    "<title>Shutter Controller - Login</title>\n"
    "<link rel=\"stylesheet\" type=\"text/css\" href=\"" RESOURCE_PROVIDER "/login.css\"/>\n"
    "</head>\n"
    "<body>\n"
    "<div class=\"login-container\">\n"
    "<h2>Shutter Controller - Login</h2>\n"
    "<form class=\"login-form\" action=\"./L\" method=\"POST\">\n"
    "<input type=\"text\" placeholder=\"Username\" name=\"username\">\n"
    "<input type=\"password\" placeholder=\"Password\" name=\"password\">\n"
    "<button type=\"submit\">Sign In</button>\n"
    "</form>\n"
    "</div>\n"
    "</body>\n"
    "</html>";

    //page showed when bad credentials were given
    const char loginFail[] PROGMEM = "<!DOCTYPE html>\n"
    "<html lang=\"en\">\n"
    "<head>\n"
    "<meta charset=\"UTF-8\">\n"
    "<meta name=\"viewport\" content=\"width=device-width, initial-scale=1.0\">\n"
    "<title>Shutter Controller - Login failed</title>\n"
    "<link rel=\"stylesheet\" type=\"text/css\" href=\"" RESOURCE_PROVIDER "/login.css\"/>\n"
    "</head>\n"
    "<body>\n"
    "<div class=\"login-container\">\n"
    "<h3>Shutter Controller - Login failed</h3>\n"
    "<form action=\"./\">\n"
    "<button type=\"submit\" class=\"login-form button\">Go back</button>\n"
    "</form>\n"
    "</div>\n"
    "</body>\n"
    "</html>";

    //the main page controlling the shutter
    const char controlPage[] PROGMEM = "<!DOCTYPE html>\n"
    "<html>\n"
    "<head>\n"
    "<title>Shutter Controller - HTML client</title>\n"
    "<link rel=\"stylesheet\" type=\"text/css\" href=\"" RESOURCE_PROVIDER "/control.css\"/>\n"
    "<script src=\"" RESOURCE_PROVIDER "/control.js\"></script>\n"
    "<script>\n"
    "function showTab(tabIndex) {\n"
    "const tabContents = document.getElementsByClassName('tab-content');\n"
    "for (let i = 0; i < tabContents.length; i++) {\n"
    "tabContents[i].classList.remove('active');\n"
    "}\n"
    "tabContents[tabIndex].classList.add('active');\n"
    "const tabs = document.getElementsByClassName('tab');\n"
    "for (let i = 0; i < tabs.length; i++) {\n"
    "tabs[i].classList.remove('active');\n"
    "}\n"
    "tabs[tabIndex].classList.add('active');\n"
    "}\n"
    "</script>\n"
    "</head>\n"
    "<body>\n"
    "<div class=\"container\">\n"
    "<div class=\"row\">\n"
    "<h2 class=\"row-item\">Shutter controller!</h2>\n"
    "<p class=\"row-item\">Hello " USER_NAME "!</p>\n"
    "<form class=\"row-item\" action=\"./O\">\n"
    "<input type=\"submit\" value=\"Sign out\">\n"
    "</form>\n"
    "</div>\n"
    "<div class=\"row\">\n"
    "<a href=\"/W\">WASM client</a>\n"
    "</div>\n"
    "<div class=\"wrapper\">\n"
    "<div class=\"tabs-container\">\n"
    "<div class=\"tabs\">\n"
    "<div class=\"tab active\" onclick=\"showTab(0)\">Setting</div>\n"
    "<div class=\"tab\" onclick=\"showTab(1)\">Timing</div>\n"
    "<div class=\"tab\" onclick=\"showTab(2)\">Zeroing</div>\n"
    "</div>\n"
    "</div>\n"
    "<div class=\"tab-contents\">\n"
    "<div class=\"tab-content active\">\n"
    "<div class=\"set-tab-content\">\n"
    "<div class=\"range-container\">\n"
    "<label class=\"range-label\" for=\"range-input\">Position:</label>\n"
    "<input type=\"range\" id=\"seekbar\" step=\"5\" min=\"0\" max=\"100\" step=\"1\" value=0>\n"
    "<span class=\"range-value\" id=\"seekbarValueText\">0%</span>\n"
    "<input id=\"setButton\" type=\"button\" value=\"Set\">\n"
    "</div>\n"
    "</div>\n"
    "</div>\n"
    "<div class=\"tab-content\">\n"
    "<div id=\"timings\">\n"
    "</div>\n"
    "<input type=\"submit\" value=\"Send\" id=\"timingButton\">\n"
    "</div>\n"
    "<div class=\"tab-content\">\n"
    "<div class=\"zero-content\">\n"
    "<button class=\"zero-button\" id=\"upButton\">Up</button>\n"
    "<button class=\"zero-button\" id=\"downButton\">Down</button>\n"
    "<button class=\"zero-button\" id=\"autoButton\">Find</button>\n"
    "</div>\n"
    "</div>\n"
    "</div>\n"
    "</div>\n"
    "<div class=\"additional-section\">\n"
    "<div class=\"state-section\">\n"
    "<div class=\"state-line\">\n"
    "<div>Current position:</div>\n"
    "<div id=\"curVal\"> - </div>\n"
    "</div>\n"
    "<div class=\"state-line\">\n"
    "<div>Server state:</div>\n"
    "<div id=\"stat\"> - </div>\n"
    "</div>\n"
    "<div class=\"state-line\">\n"
    "<div>Server startup time:</div>\n"
    "<div id=\"startup\"> - </div>\n"
    "</div>\n"
    "</div>\n"
    "<div class=\"message-column\">\n"
    "<h5>Messages:</h5>\n"
    "<table id=\"messages\">\n"
    "<tr>\n"
    "<th class=\"message-index-width\">ID</th>\n"
    "<th class=\"message-content-width\">Message</th>\n"
    "<th class=\"message-date-width\">Date</th>\n"
    "</tr>\n"
    "</table>\n"
    "</div>\n"
    "</div>\n"
    "</div>\n"
    "</body>\n"
    "</html>";

    //the page containing the wasm module
    const char wasmPage[] PROGMEM = "<!DOCTYPE html>\n"
    "<html>\n"
    "<head>\n"
    "<title>Shutter Controller - WASM client</title>\n"
    "<meta name=\"viewport\" content=\"width=device-width, initial-scale=1.0\">\n"
    "<link rel=\"stylesheet\" type=\"text/css\" href=\"" RESOURCE_PROVIDER "/wasm-client.css\"/>\n"
    "</head>\n"
    "<body>\n"
    "<div id=\"header\">\n"
    "<div class=\"row\">\n"
    "<h2 class=\"row-item\">Shutter controller!</h2>\n"
    "<p class=\"row-item\">Hello " USER_NAME "!</p>\n"
    "<form class=\"row-item\" action=\"./O\">\n"
    "<input type=\"submit\" value=\"Sign out\">\n"
    "</form>\n"
    "</div>\n"
    "<div class=\"row\">\n"
    "<a href=\"/\">HTML+JS client</a>\n"
    "</div>\n"
    "<canvas id=\"canvas\" class=\"emscripten\" oncontextmenu=\"event.preventDefault()\" tabindex=-1>Canvas for WASM.</canvas>\n"
    "</div>\n"
    "<script type='text/javascript'>\n"
    "var Module = {\n"
    "canvas: (function() { return document.getElementById('canvas'); })()\n"
    "};\n"
    "</script>\n"
    "<script async type=\"text/javascript\" src=\"" RESOURCE_PROVIDER "/ShutterClient.js\" ></script>\n"
    "</body>\n"
    "</html>";

    //worker/thread module for the wasm module,  TODO:should be served from an external server
    const char wasmWorker[] PROGMEM = "var Module={},ENVIRONMENT_IS_NODE=\"object\"==typeof process&&\"object\"==typeof process.versions&&\"string\"==typeof process.versions.node;\n"
    "if(ENVIRONMENT_IS_NODE){var nodeWorkerThreads=require(\"worker_threads\"),parentPort=nodeWorkerThreads.parentPort;parentPort.on(\"message\",a=>onmessage({data:a}));var fs=require(\"fs\");Object.assign(global,{self:global,require,Module,location:{href:__filename},Worker:nodeWorkerThreads.Worker,importScripts:a=>(0,eval)(fs.readFileSync(a,\"utf8\")+\"//# sourceURL=\"+a),postMessage:a=>parentPort.postMessage(a),performance:global.performance||{now:Date.now}})}var initializedJS=!1;\n"
    "function assert(a,c){a||abort(\"Assertion failed: \"+c)}function threadPrintErr(){var a=Array.prototype.slice.call(arguments).join(\" \");ENVIRONMENT_IS_NODE?fs.writeSync(2,a+\"\\n\"):console.error(a)}function threadAlert(){var a=Array.prototype.slice.call(arguments).join(\" \");postMessage({cmd:\"alert\",text:a,threadId:Module._pthread_self()})}var out=()=>{throw\"out() is not defined in worker.js.\";},err=threadPrintErr;self.alert=threadAlert;var dbg=threadPrintErr;\n"
    "Module.instantiateWasm=(a,c)=>{var b=Module.wasmModule;Module.wasmModule=null;a=new WebAssembly.Instance(b,a);return c(a)};self.onunhandledrejection=a=>{throw a.reason??a;};\n"
    "function handleMessage(a){try{if(\"load\"===a.data.cmd){let b=[];self.onmessage=d=>b.push(d);self.startWorker=d=>{postMessage({cmd:\"loaded\"});for(let e of b)handleMessage(e);self.onmessage=handleMessage};Module.wasmModule=a.data.wasmModule;for(const d of a.data.handlers)Module[d]=(...e)=>{postMessage({cmd:\"callHandler\",handler:d,args:e})};Module.wasmMemory=a.data.wasmMemory;Module.buffer=Module.wasmMemory.buffer;Module.workerID=a.data.workerID;Module.ENVIRONMENT_IS_PTHREAD=!0;if(\"string\"==typeof a.data.urlOrBlob)importScripts(a.data.urlOrBlob);\n"
    "else{var c=URL.createObjectURL(a.data.urlOrBlob);importScripts(c);URL.revokeObjectURL(c)}}else if(\"run\"===a.data.cmd){Module.__emscripten_thread_init(a.data.pthread_ptr,0,0,1);Module.__emscripten_thread_mailbox_await(a.data.pthread_ptr);assert(a.data.pthread_ptr);Module.establishStackSpace();Module.PThread.receiveObjectTransfer(a.data);Module.PThread.threadInitTLS();initializedJS||=!0;try{Module.invokeEntryPoint(a.data.start_routine,a.data.arg)}catch(b){if(\"unwind\"!=b)throw b;}}else\"cancel\"===a.data.cmd?\n"
    "Module._pthread_self()&&Module.__emscripten_thread_exit(-1):\"setimmediate\"!==a.data.target&&(\"checkMailbox\"===a.data.cmd?initializedJS&&Module.checkMailbox():a.data.cmd&&(err(\"worker.js received unknown command \"+a.data.cmd),err(a.data)))}catch(b){throw err(\"worker.js onmessage() captured an uncaught exception: \"+b),b&&b.stack&&err(b.stack),Module.__emscripten_thread_crashed&&Module.__emscripten_thread_crashed(),b;}}self.onmessage=handleMessage;";
}

#endif