#ifndef BROWSERCLIENT_H
#define BROWSERCLIENT_H

//The sign-in page
const char loginPage[] PROGMEM = "<!DOCTYPE html>\n"
"<html>\n"
"    <head>\n"
"    </head>\n"
"    <body>\n"
"        <form action=\"./L\" method=\"post\">\n"
"	        <label for=\"fname\">User:</label><br>\n"
"	        <input type=\"text\" name=\"username\" value=\"\"><br><br>\n"
"	        <label for=\"fname\">Password:</label><br>\n"
"	    <input type=\"password\" name=\"password\" value=\"\"><br><br>\n"
"	    <input type=\"submit\" value=\"Sign-in\">\n"
"        </form>\n"
"    </body>\n"
"</html>\n";

//page showed when bad credentials given
const char loginFail[] PROGMEM ="<!DOCTYPE html>\n"
"<html>\n"
"    <head>\n"
"    </head>\n"
"    <body>\n"
"	    <h5>Login failed!</h5>\n"
"        <form action=\"/\">\n"
"            <input type=\"submit\" value=\"Back\">\n"
"        </form>\n"
"    </body>\n"
"</html>\n";

//the main page controlling the shutter
const char controlPage[] PROGMEM = "<!DOCTYPE html>\n"
"<head>\n"
"<style>\n"
"body {font-family: Arial;}\n"
"\n"
"/* Style the tab */\n"
".tab {\n"
"overflow: hidden;\n"
"border: 1px solid #ccc;\n"
"background-color: #f1f1f1;\n"
"}\n"
"\n"
"/* Style the buttons inside the tab */\n"
".tab button {\n"
"background-color: inherit;\n"
"float: left;\n"
"border: none;\n"
"outline: none;\n"
"cursor: pointer;\n"
"padding: 14px 16px;\n"
"transition: 0.3s;\n"
"font-size: 17px;\n"
"}\n"
"\n"
"/* Change background color of buttons on hover */\n"
".tab button:hover {\n"
"background-color: #ddd;\n"
"}\n"
"\n"
"/* Create an active/current tablink class */\n"
".tab button.active {\n"
"background-color: #ccc;\n"
"}\n"
"\n"
"/* Style the tab content */\n"
".tabcontent {\n"
"display: none;\n"
"padding: 6px 12px;\n"
"border: 1px solid #ccc;\n"
"border-top: none;\n"
"}\n"
"</style>\n"
"\n"
"<script>\n"
"const NR_OF_TIMINGS = 6;\n"
"const NR_OF_MESSAGES = 10;\n"
"\n"
"var currentValue;\n"
"var startup;\n"
"\n"
"var stateMessage;\n"
"var messages;\n"
"var timings;\n"
"var timingSeekbars = [];\n"
"\n"
"var longrequest = false;\n"
"var failureCounter = 0;\n"
"\n"
"var timingButton;\n"
"var setButton;\n"
"var upButton;\n"
"var downButton;\n"
"var autoButton;\n"
"\n"
"var queue = [];\n"
"var currentRequest = null;\n"
"\n"
"function disableGui(){\n"
"for (var i = 0; i < timings.children.length; i++) {\n"
"for(var j = 0; j < timings.children[i].children.length; j++) {\n"
"timings.children[i].children[j].disabled = true;\n"
"}\n"
"}\n"
"\n"
"timingButton.disabled = true;\n"
"setButton.disabled = true;\n"
"upButton.disabled = true;\n"
"downButton.disabled = true;\n"
"autoButton.disabled = true;\n"
"\n"
"seekbar.disabled = true;\n"
"};\n"
"\n"
"function enableGUI(){\n"
"for (var i = 0; i < timings.children.length; i++) {\n"
"for(var j = 0; j < timings.children[i].children.length; j++) {\n"
"timings.children[i].children[j].disabled = false;\n"
"}\n"
"}\n"
"\n"
"timingButton.disabled = false;\n"
"setButton.disabled = false;\n"
"upButton.disabled = false;\n"
"downButton.disabled = false;\n"
"autoButton.disabled = false;\n"
"\n"
"seekbar.disabled = false;\n"
"};\n"
"\n"
"function dequeue() {\n"
"if (queue.length > 0) {\n"
"stateMessage.innerText = \"Syncing in progress...\";\n"
"\n"
"currentRequest = queue.shift();\n"
"currentRequest.request.timeout = 12000;\n"
"\n"
"if (currentRequest.request.onload == null) {\n"
"currentRequest.request.onload = function() {\n"
"var responseObject = JSON.parse(currentRequest.request.response);\n"
"parseGenericResponse(responseObject[\"G\"]);\n"
"currentRequest = null;\n"
"failureCounter = 0;\n"
"dequeue();\n"
"}\n"
"\n"
"disableGui();\n"
"}\n"
"\n"
"currentRequest.request.ontimeout = function() {\n"
"stateMessage.innerText = \"The server is not available.\";\n"
"disableGui();\n"
"failureCounter++;\n"
"currentRequest = null;\n"
"dequeue();\n"
"}\n"
"\n"
"currentRequest.request.onerror = function() {\n"
"stateMessage.innerText = \"Error while communicating.\";\n"
"disableGui();\n"
"failureCounter++;\n"
"currentRequest = null;\n"
"dequeue();\n"
"}\n"
"\n"
"currentRequest.request.onreadystatechange = function() {\n"
"if (this.readyState !== 4) {\n"
"return;\n"
"}\n"
"\n"
"if (this.status == \"302\") {\n"
"location.reload();\n"
"}\n"
"}\n"
"\n"
"if (currentRequest.body == null) {\n"
"currentRequest.request.open(\"GET\", currentRequest.path);\n"
"currentRequest.request.send();\n"
"}\n"
"else {\n"
"currentRequest.request.open(\"POST\", currentRequest.path);\n"
"currentRequest.request.send(currentRequest.body);\n"
"}                \n"
"}\n"
"};\n"
"\n"
"function enqueue(requestObject) {\n"
"queue.push(requestObject);\n"
"if(queue.length == 1 && currentRequest == null){\n"
"dequeue();\n"
"}\n"
"};\n"
"\n"
"function parseMessages(messageObject) {\n"
"startup.innerText = messageObject[\"S\"];\n"
"\n"
"for (var key in messageObject[\"M\"]) {\n"
"var keyInt = parseInt(key);\n"
"var formattedMessage = getFormattedMessage(messageObject[\"M\"][key][\"T\"], messageObject[\"M\"][key][\"R\"], messageObject[\"M\"][key][\"A\"]);\n"
"\n"
"messages.childNodes[keyInt+2].innerHTML = `<td style=\"width: 16%; text-align: center\">${keyInt+1}.</td>\n"
"<td style=\"width: 32%; text-align: left\">${formattedMessage}</td>\n"
"<td style=\"width: 42%; text-align: left\">${messageObject[\"M\"][key][\"D\"]}</td>`;                \n"
"}\n"
"}\n"
"\n"
"function parseTiming(timingsObject) {\n"
"for (var key in timingsObject) {\n"
"var timingObject = timingsObject[key];\n"
"var keyInt = parseInt(key);\n"
"\n"
"var activeBox = document.getElementById(`toggle${keyInt}`);\n"
"activeBox.checked = timingObject[\"A\"];\n"
"\n"
"var timeSet = document.getElementById(`timeSet${keyInt}`);\n"
"\n"
"var hourString = String(timingObject[\"H\"]);\n"
"hourString = hourString.length == 1 ? \"0\" + hourString : hourString;\n"
"\n"
"var minuteString = String(timingObject[\"M\"]);\n"
"minuteString = minuteString.length == 1 ? \"0\" + minuteString : minuteString;\n"
"\n"
"timeSet.value = hourString + \":\" + minuteString;\n"
"\n"
"var seekbar = document.getElementById(`tseekbar${keyInt}`);\n"
"seekbar.value = timingObject[\"V\"];\n"
"\n"
"var seekbarText = document.getElementById(`seekbarValue${keyInt}`);\n"
"seekbarText.innerText = timingObject[\"V\"];\n"
"\n"
"for(var i = 0; i < 7; i++) {\n"
"var dayBox = document.getElementById(`day${keyInt}_${i}`);\n"
"\n"
"if (timingObject[\"D\"][i] == \"T\") {\n"
"dayBox.checked = true;    \n"
"}   \n"
"else{\n"
"dayBox.checked = false;\n"
"}\n"
"}\n"
"}\n"
"}\n"
"\n"
"function postUR() {\n"
"var zeroObject = new Object();\n"
"var zeroJObject = {\"Z\" : \"up\"};\n"
"zeroObject.request = new XMLHttpRequest();\n"
"zeroObject.path = \"/Z\";\n"
"zeroObject.body = JSON.stringify(zeroJObject);\n"
"enqueue(zeroObject);\n"
"};\n"
"function postDR() {\n"
"var zeroObject = new Object();\n"
"var zeroJObject = {\"Z\" : \"down\"};\n"
"zeroObject.request = new XMLHttpRequest();\n"
"zeroObject.path = \"./Z\";\n"
"zeroObject.body = JSON.stringify(zeroJObject);\n"
"enqueue(zeroObject);\n"
"};        \n"
"function postAR() {\n"
"var zeroObject = new Object();\n"
"var zeroJObject = {\"Z\" : \"find\"};\n"
"zeroObject.request = new XMLHttpRequest();\n"
"zeroObject.path = \"./Z\";\n"
"zeroObject.body = JSON.stringify(zeroJObject);\n"
"enqueue(zeroObject);\n"
"};\n"
"\n"
"function createStatusRequestObject() {\n"
"var statusRequestObject = new Object();\n"
"\n"
"var statusRequest = new XMLHttpRequest();\n"
"statusRequest.onload = function() {\n"
"var responseObject = JSON.parse(this.response);\n"
"parseGenericResponse(responseObject[\"G\"]);\n"
"currentRequest = null;\n"
"\n"
"if (longrequest) {\n"
"stateMessage.innerText = \"Syncing in progress...\";\n"
"disableGui();\n"
"}\n"
"\n"
"dequeue();\n"
"};\n"
"\n"
"statusRequestObject.request = statusRequest;\n"
"statusRequestObject.path = \"/S\";\n"
"statusRequestObject.body = null;\n"
"\n"
"return statusRequestObject;\n"
"};\n"
"\n"
"function getStatus() {\n"
"var statusRequestObject = createStatusRequestObject();\n"
"enqueue(statusRequestObject);\n"
"}\n"
"\n"
"function parseGenericResponse(responseObject) {\n"
"var retrytime = responseObject[\"R\"];\n"
"retrytime = parseInt(retrytime);\n"
"\n"
"if (retrytime > 0 && queue.length == 0) {\n"
"setTimeout(getStatus, (retrytime * 1000));\n"
"return;\n"
"}\n"
"else if (retrytime > 0 && queue.length > 0) {\n"
"return;\n"
"}\n"
"else if (queue.length == 0) {\n"
"enableGUI();\n"
"}\n"
"\n"
"longrequest = false;\n"
"var value = parseInt(responseObject[\"V\"]);\n"
"seekbarValue.innerText = value;\n"
"seekbar.value = value;\n"
"\n"
"stateMessage.innerText = \"The server is available!\";\n"
"currentValue.innerText = value;\n"
"\n"
"parseMessages(responseObject[\"M\"]);            \n"
"};\n"
"\n"
"function parseDump(dump) {\n"
"var dumpObject = JSON.parse(dump);\n"
"var genericObject = dumpObject[\"G\"];\n"
"parseGenericResponse(genericObject);\n"
"var timingObject = dumpObject[\"T\"];\n"
"parseTiming(timingObject);\n"
"}\n"
"\n"
"function sendDumpRequest() {\n"
"var dumpRequest = new XMLHttpRequest();\n"
"dumpRequest.onload = function() {\n"
"parseDump(dumpRequest.response);\n"
"currentRequest = null;\n"
"enableGUI();\n"
"dequeue();\n"
"};\n"
"\n"
"var dumpRequestObject = new Object();\n"
"dumpRequestObject.request = dumpRequest;\n"
"dumpRequestObject.path = \"/D\";\n"
"dumpRequestObject.body = null;\n"
"enqueue(dumpRequestObject);\n"
"}\n"
"\n"
"function postValue() {            \n"
"var setJObject = {\"V\" : seekbar.value};            \n"
"var setRequestObject = new Object();\n"
"\n"
"setRequestObject.request = new XMLHttpRequest();\n"
"setRequestObject.path = \"/V\";\n"
"setRequestObject.body = JSON.stringify(setJObject);\n"
"enqueue(setRequestObject);\n"
"}\n"
"\n"
"function postTimings() {\n"
"var timingstJObject = serializeTimings();\n"
"var timingsRequestObject = new Object();\n"
"\n"
"timingsRequestObject.request = new XMLHttpRequest();\n"
"timingsRequestObject.path = \"/T\";\n"
"timingsRequestObject.body = JSON.stringify(timingstJObject);\n"
"enqueue(timingsRequestObject);\n"
"}\n"
"\n"
"function initMessages() {\n"
"messages = document.getElementById(\"messages\");\n"
"for (var i = 0; i < NR_OF_MESSAGES; i++) {\n"
"var tr = document.createElement('tr');\n"
"\n"
"tr.innerHTML =`<td style=\"width: 16%; text-align: center\">${i+1}.</td>\n"
"<td style=\"width: 42%; text-align: left\">-</td>\n"
"<td style=\"width: 42%; text-align: left\">-</td>`;\n"
"\n"
"messages.appendChild(tr);\n"
"}   \n"
"}\n"
"\n"
"function initTimings() {\n"
"timings = document.getElementById(\"timings\");\n"
"\n"
"for (var i = 0; i < NR_OF_TIMINGS; i++) {\n"
"var div = document.createElement('div');\n"
"div.style = \"height:30px;\";\n"
"div.innerHTML = `<p style=\"display:inline-block; padding-left: 2em;\">${i+1}.</p>\n"
"<input id=\"timeSet${i}\" type=\"time\" style=\"display:inline-block; padding-left: 1em;\">\n"
"<input type=\"checkbox\" id=\"day${i}_0\" style=\"display:inline-block; padding-left: 1em;\">\n"
"<label for=\"day${i}_0\">M</label>\n"
"<input type=\"checkbox\" id=\"day${i}_1\" style=\"display:inline-block; padding-left: 1em;\">\n"
"<label for=\"day${i}_1\">Tu</label>\n"
"<input type=\"checkbox\" id=\"day${i}_2\" style=\"display:inline-block; padding-left: 1em;\">\n"
"<label for=\"day${i}_2\">W</label>\n"
"<input type=\"checkbox\" id=\"day${i}_3\" style=\"display:inline-block; padding-left: 1em;\">\n"
"<label for=\"day${i}_3\">Th</label>\n"
"<input type=\"checkbox\" id=\"day${i}_4\" style=\"display:inline-block; padding-left: 1em;\">\n"
"<label for=\"day${i}_4\">F</label>\n"
"<input type=\"checkbox\" id=\"day${i}_5\" style=\"display:inline-block; padding-left: 1em;\">\n"
"<label for=\"day${i}_5\">Sa</label>\n"
"<input type=\"checkbox\" id=\"day${i}_6\" style=\"display:inline-block; padding-left: 1em;\">\n"
"<label for=\"day${i}_6\">Su</label>\n"
"<input type=\"range\" min=\"0\" max=\"100\" name=\"V\" id=\"tseekbar${i}\" value=\"\" style=\"display:inline-block;\">\n"
"<div id=\"seekbarValue${i}\" style=\"display:inline-block\"></div> &nbsp;\n"
"<input type=\"checkbox\" style=\"display:inline-block; padding-left: 1em;\" id=\"toggle${i}\">\n"
"<label for=\"toggle${i}\">Active</label>`;\n"
"timings.appendChild(div);\n"
"}\n"
"\n"
"for (var i = 0; i < NR_OF_TIMINGS; i++) {\n"
"var seekbar = document.getElementById(`tseekbar${i}`);\n"
"seekbar.customLabel = document.getElementById(`seekbarValue${i}`);\n"
"timingSeekbars.push(seekbar);                \n"
"\n"
"timingSeekbars[i].oninput = function() {\n"
"this.customLabel.innerText = this.value;\n"
"};\n"
"}\n"
"}\n"
"\n"
"function serializeTimings() {\n"
"var timingsObject = {};\n"
"\n"
"for(var i = 0; i < NR_OF_TIMINGS; i++) {\n"
"var timingObject = {};\n"
"\n"
"var timeInput = document.getElementById(`timeSet${i}`).value;\n"
"var times = timeInput.split(\":\");\n"
"\n"
"var days = \"\";\n"
"\n"
"for (var j = 0; j < 7; j++) {\n"
"var dayBox = document.getElementById(`day${i}_${j}`);\n"
"\n"
"if (dayBox.checked) {\n"
"days += \"T\";\n"
"}\n"
"else {\n"
"days += \"F\";\n"
"}\n"
"}\n"
"\n"
"var activeBox = document.getElementById(`toggle${i}`);\n"
"var seekbar = document.getElementById(`tseekbar${i}`);\n"
"\n"
"timingObject[\"H\"] = parseInt(times[0]);\n"
"timingObject[\"M\"] = parseInt(times[1]);\n"
"timingObject[\"D\"] = days;\n"
"timingObject[\"A\"] = activeBox.checked;\n"
"timingObject[\"V\"] = seekbar.value;\n"
"\n"
"timingsObject[String(i)] =  timingObject;\n"
"}\n"
"\n"
"return timingsObject;\n"
"}\n"
"\n"
"function getFormattedMessage(T, R, A) {\n"
"if (T == \"E\"){\n"
"return \"-\";\n"
"}\n"
"\n"
"if (T == \"I\"){\n"
"return \"Server startup.\";\n"
"}\n"
"\n"
"if (T == \"J\"){\n"
"return \"JSON Error: \" + R + \", \" + A;\n"
"}\n"
"\n"
"if (T == \"Z\"){\n"
"if (R == \"F\") {\n"
"return \"Nulling failed.\";\n"
"}\n"
"\n"
"if (R == \"O\") {\n"
"if (A == \"U\") {\n"
"return \"Nulling: up.\";\n"
"}\n"
"else if (A == \"D\") {\n"
"return \"Nulling: down.\";\n"
"}\n"
"}\n"
"}\n"
"\n"
"if (T == \"T\") {\n"
"return \"\" + R + \". timing set: \" + A + \"%.\";\n"
"}\n"
"\n"
"if (T == \"S\") {\n"
"if (R == \"M\") {\n"
"return \"Manual set: \" + A + \"%.\";\n"
"}\n"
"\n"
"if (R == \"Z\") {\n"
"return \"Position found: \" + A + \"%.\";\n"
"}\n"
"\n"
"if (R == \"T\") {\n"
"return \"Timings updated.\";\n"
"}\n"
"}\n"
"\n"
"return \"Unknown event: \" + T + \", \" + R + \", \" + A;\n"
"}\n"
"\n"
"window.onload = function(){\n"
"currentValue = document.getElementById(\"curVal\");\n"
"startup = document.getElementById(\"startup\");\n"
"stateMessage = document.getElementById(\"stat\");\n"
"\n"
"seekbar = document.getElementById(\"seekbar\");\n"
"seekbar.oninput = function() {\n"
"seekbarValue.innerText = seekbar.value;\n"
"};\n"
"\n"
"timingButton = document.getElementById(\"timingButton\");\n"
"setButton = document.getElementById(\"setButton\");\n"
"upButton = document.getElementById(\"upButton\");\n"
"downButton = document.getElementById(\"downButton\");\n"
"autoButton = document.getElementById(\"autoButton\");\n"
"\n"
"initMessages();\n"
"initTimings();\n"
"disableGui();\n"
"sendDumpRequest();\n"
"\n"
"var i = setInterval(function() {\n"
"if (queue.length == 0 && longrequest != true && currentRequest == null && failureCounter < 5) {\n"
"var statusRequestObject = createStatusRequestObject();\n"
"enqueue(statusRequestObject);\n"
"}\n"
"}, 30000);\n"
"};\n"
"</script>\n"
"</head>\n"
"<body>\n"
"<div style=\"display:inline-flex;\">\n"
"<h2 style=\"display:inline-block;\">Shutter Controller!</h2>\n"
"&nbsp; &nbsp;&nbsp; &nbsp;&nbsp; &nbsp;\n"
"<p style=\"display:inline-block;margin-top: 6%;margin-left:3em;\">Hello "USER_NAME"!</p>\n"
"&nbsp; &nbsp;\n"
"<form action=\"./O\">\n"
"<input type=\"submit\" style=\"display:inline-block; margin-top: 40%;\" value=\"Sign out\">\n"
"</form>            \n"
"</div>\n"
"\n"
"<div class=\"tab\" style = \"width: 61.3%;\">\n"
"<button class=\"tablinks\" onclick=\"openTab(event, 'set')\">Set</button>\n"
"<button class=\"tablinks\" onclick=\"openTab(event, 'time')\">Timing</button>\n"
"<button class=\"tablinks\" onclick=\"openTab(event, 'zero')\">Null</button>\n"
"</div>\n"
"\n"
"<div id=\"set\" class=\"tabcontent\" style=\"width: 60%;\">\n"
"<h5 style=\"height:0px;\">Timings: </h5>\n"
"<div style=\"display:inline-flex;\">\n"
"<label for=\"fname\">Set:</label><br>\n"
"<input type=\"range\" min=\"0\" max=\"100\" name=\"V\" id=\"seekbar\" value=\"\"><br>\n"
"<div id=\"seekbarValue\"></div> &nbsp;\n"
"<button id=\"setButton\" onclick=\"postValue()\">Send</button>\n"
"</div><br><br>\n"
"<div style=\"display:inline-flex;\">\n"
"<div>Current value: &nbsp;</div>\n"
"<div id=\"curVal\"></div>\n"
"</div><br><br>\n"
"</div>\n"
"\n"
"<div id=\"time\" class=\"tabcontent\" style=\"width: 60%;\">\n"
"<h5 style=\"height:0px;\">Timings: </h5>\n"
"\n"
"<div id=\"timings\">\n"
"\n"
"</div>\n"
"\n"
"<br>\n"
"<br>\n"
"<input type=\"submit\" value=\"Send\" onclick=\"postTimings()\" style=\"margin-left: 2em;\" id=\"timingButton\">\n"
"\n"
"</div>\n"
"\n"
"<div id=\"zero\" class=\"tabcontent\" style=\"width: 60%;\">\n"
"<h5 style=\"height: 10px;\">Type of null:</h5>\n"
"<button id=\"upButton\" onclick=\"postUR()\" style=\"margin-left: 2em\">Up</button>\n"
"<button id=\"downButton\" onclick=\"postDR()\" style=\"margin-left: 2em\">Down</button>\n"
"<button id=\"autoButton\" onclick=\"postAR()\" style=\"margin-left: 2em\">Auto</button>\n"
"<br>\n"
"</div>\n"
"\n"
"<div style=\"display:inline-flex;width: 100%;\">\n"
"<div style=\"width:40%;\">\n"
"<h5 style=\"height:0px;\">Messages: </h5>\n"
"<table style=\"width: 100%;\" id=\"messages\">\n"
"<tr>\n"
"<th style=\"width: 16%;\">ID</th>\n"
"<th style=\"width: 32%; text-align: left;\">Message</th>\n"
"<th style=\"width: 42%; text-align: left;\">Time</th>\n"
"</tr>\n"
"</table>\n"
"</div>\n"
"\n"
"<div style=\"width:20%;\">\n"
"<br><br>\n"
"<div style=\"display:inline-flex;\">\n"
"<div>State: &nbsp; </div>\n"
"<div id=\"stat\"></div>\n"
"</div><br><br>\n"
"\n"
"<div style=\"display:inline-flex;\">\n"
"<div>Startup: &nbsp; </div>\n"
"<div id=\"startup\"></div>\n"
"</div><br><br>\n"
"</div>\n"
"\n"
"</div>\n"
"<br>\n"
"\n"
"<script>\n"
"function openTab(evt, cityName) {\n"
"var i, tabcontent, tablinks;\n"
"tabcontent = document.getElementsByClassName(\"tabcontent\");\n"
"for (i = 0; i < tabcontent.length; i++) {\n"
"tabcontent[i].style.display = \"none\";\n"
"}\n"
"tablinks = document.getElementsByClassName(\"tablinks\");\n"
"for (i = 0; i < tablinks.length; i++) {\n"
"tablinks[i].className = tablinks[i].className.replace(\" active\", \"\");\n"
"}\n"
"document.getElementById(cityName).style.display = \"block\";\n"
"evt.currentTarget.className += \" active\";\n"
"}\n"
"</script>\n"
"</body>\n"
"</html>\n"
"</html>\n";

#endif