#ifndef BROWSERCLIENT_H
#define BROWSERCLIENT_H

//The sign-in page
const char loginPage[] PROGMEM = "<!DOCTYPE html>\n"
"<html>\n"
"    <head>\n"
"       <link rel=\"shortcut icon\" href=\"data:image/x-icon;base64,iVBORw0KGgoAAAANSUhEUgAAAAgAAAAIBAMAAAA2IaO4AAAAAXNSR0IArs4c6QAAAARnQU1BAACxjwv8YQUAAAAwUExURZuYmp6amqKfn6GeoKajo6WgoamlpqunqK6rq66qq66rrLGurrKvsbWytLWxsri1tmaDmxsAAAAJcEhZcwAADsIAAA7CARUoSoAAAAAtSURBVBjTY7j///9/BkZBQUEIyzTEVYnh3N1z7xjSy9JcGFbtntHFsLw8LQ0AfZASPN7lR7sAAAAASUVORK5CYII=\" />"
"    </head>\n"
"    <body>\n"
"        <form action=\"./L\" method=\"post\">\n"
"	        <label for=\"fname\">User:</label><br>\n"
"	        <input type=\"text\" name=\"username\" value=\"\"><br><br>\n"
"	        <label for=\"fname\">Password:</label><br>\n"
"	    <input type=\"password\" name=\"password\" value=\"\"><br><br>\n"
"	    <input type=\"submit\" value=\"Sign-in\">\n"
"        </form>\n"
"    </body>\n"
"</html>\n";

//page showed when bad credentials given
const char loginFail[] PROGMEM = "<!DOCTYPE html>\n"
"<html>\n"
"    <head>\n"
"       <link rel=\"shortcut icon\" href=\"data:image/x-icon;base64,iVBORw0KGgoAAAANSUhEUgAAAAgAAAAIBAMAAAA2IaO4AAAAAXNSR0IArs4c6QAAAARnQU1BAACxjwv8YQUAAAAwUExURZuYmp6amqKfn6GeoKajo6WgoamlpqunqK6rq66qq66rrLGurrKvsbWytLWxsri1tmaDmxsAAAAJcEhZcwAADsIAAA7CARUoSoAAAAAtSURBVBjTY7j///9/BkZBQUEIyzTEVYnh3N1z7xjSy9JcGFbtntHFsLw8LQ0AfZASPN7lR7sAAAAASUVORK5CYII=\" />"
"    </head>\n"
"    <body>\n"
"	    <h5>Login failed!</h5>\n"
"        <form action=\"/\">\n"
"            <input type=\"submit\" value=\"Back\">\n"
"        </form>\n"
"    </body>\n"
"</html>\n";

//the main page controlling the shutter
const char controlPage[] PROGMEM = "<!DOCTYPE html>\n"
"<head>\n"
"<link rel=\"shortcut icon\" href=\"data:image/x-icon;base64,iVBORw0KGgoAAAANSUhEUgAAAAgAAAAIBAMAAAA2IaO4AAAAAXNSR0IArs4c6QAAAARnQU1BAACxjwv8YQUAAAAwUExURZuYmp6amqKfn6GeoKajo6WgoamlpqunqK6rq66qq66rrLGurrKvsbWytLWxsri1tmaDmxsAAAAJcEhZcwAADsIAAA7CARUoSoAAAAAtSURBVBjTY7j///9/BkZBQUEIyzTEVYnh3N1z7xjSy9JcGFbtntHFsLw8LQ0AfZASPN7lR7sAAAAASUVORK5CYII=\">\n"
"<style>\n"
"body {font-family: Arial;}\n"
"\n"
".tab {\n"
"overflow: hidden;\n"
"border: 1px solid #ccc;\n"
"background-color: #f1f1f1;\n"
"}\n"
"\n"
".tab button {\n"
"background-color: inherit;\n"
"float: left;\n"
"border: none;\n"
"outline: none;\n"
"cursor: pointer;\n"
"padding: 14px 16px;\n"
"transition: 0.3s;\n"
"font-size: 17px;\n"
"}\n"
"\n"
".tab button:hover {\n"
"background-color: #ddd;\n"
"}\n"
"\n"
".tab button.active {\n"
"background-color: #ccc;\n"
"}\n"
"\n"
".tabcontent {\n"
"display: none;\n"
"padding: 6px 12px;\n"
"border: 1px solid #ccc;\n"
"border-top: none;\n"
"}\n"
"</style>\n"
"<script>\n"
"var d,g,h,k,n,p=[],q,r,v=!1,w=0,x,y,z,A,B,C=[],D=null;function E(){for(var a=0;a<n.children.length;a++)for(var b=0;b<n.children[a].children.length;b++)n.children[a].children[b].disabled=!0;x.disabled=!0;y.disabled=!0;z.disabled=!0;A.disabled=!0;B.disabled=!0;q.disabled=!0}function F(){for(var a=0;a<n.children.length;a++)for(var b=0;b<n.children[a].children.length;b++)n.children[a].children[b].disabled=!1;x.disabled=!1;y.disabled=!1;z.disabled=!1;A.disabled=!1;B.disabled=!1;q.disabled=!1}\n"
"function G(){0<C.length&&(h.innerText=\"Syncing in progress...\",D=C.shift(),D.request.timeout=12E3,null==D.request.onload&&(D.request.onload=function(){null!=this.response&&\"\"!=this.response||location.reload();try{var a=JSON.parse(this.response);H(a.G)}catch(b){location.reload()}D=null;w=0;G()},E()),D.request.ontimeout=function(){h.innerText=\"The server is not available.\";E();w++;D=null;G()},D.request.onerror=function(){h.innerText=\"Error while communicating.\";E();w++;D=null;G()},D.request.onreadystatechange=\n"
"function(){4===this.readyState&&\"302\"==this.status&&location.reload()},null==D.body?(D.request.open(\"GET\",D.path),D.request.send()):(D.request.open(\"POST\",D.path),D.request.send(D.body)))}function I(a){C.push(a);1==C.length&&null==D&&G()}function J(){var a={};a.request=new XMLHttpRequest;a.path=\"/Z\";a.body=JSON.stringify({Z:\"up\"});I(a)}function K(){var a={};a.request=new XMLHttpRequest;a.path=\"./Z\";a.body=JSON.stringify({Z:\"down\"});I(a)}\n"
"function L(){var a={};a.request=new XMLHttpRequest;a.path=\"./Z\";a.body=JSON.stringify({Z:\"find\"});I(a)}function M(){var a={},b=new XMLHttpRequest;b.onload=function(){null!=this.response&&\"\"!=this.response||location.reload();try{var c=JSON.parse(this.response);H(c.G)}catch(l){location.reload()}D=null;v&&(h.innerText=\"Syncing in progress...\",E());G()};a.request=b;a.path=\"/S\";a.body=null;return a}function N(){var a=M();I(a)}\n"
"function H(a){var b=a.R;b=parseInt(b);if(0<b&&0==C.length)setTimeout(N,1E3*b);else if(!(0<b&&0<C.length)){0==C.length&&F();v=!1;b=parseInt(a.V);r.innerText=b;q.value=b;h.innerText=\"The server is available!\";d.innerText=b;a=a.M;g.innerText=a.S;for(var c in a.M)b=parseInt(c),k.childNodes[b+2].innerHTML=`<td style=\"width: 16%; text-align: center\">${b+1}.</td>\n"
"<td style=\"width: 32%; text-align: left\">${O(a.M[c].T,a.M[c].R,a.M[c].A)}</td>\n"
"<td style=\"width: 42%; text-align: left\">${a.M[c].D}</td>`}}\n"
"function P(){var a=new XMLHttpRequest;a.onload=function(){var c=JSON.parse(a.response);H(c.G);c=c.T;for(var l in c){var e=c[l],f=parseInt(l);document.getElementById(`toggle${f}`).checked=e.A;var m=document.getElementById(`timeSet${f}`),t=String(e.H);t=1==t.length?\"0\"+t:t;var u=String(e.M);u=1==u.length?\"0\"+u:u;m.value=t+\":\"+u;document.getElementById(`tseekbar${f}`).value=e.V;document.getElementById(`seekbarValue${f}`).innerText=e.V;for(m=0;7>m;m++)document.getElementById(`day${f}_${m}`).checked=\"T\"==\n"
"e.D[m]?!0:!1}D=null;F();G()};var b={};b.request=a;b.path=\"/D\";b.body=null;I(b)}function Q(){var a={V:q.value},b={};b.request=new XMLHttpRequest;b.path=\"/V\";b.body=JSON.stringify(a);I(b)}\n"
"function R(){a:{var a={};for(var b=0;6>b;b++){for(var c={},l=document.getElementById(`timeSet${b}`).value.split(\":\"),e=\"\",f=0;7>f;f++)e=document.getElementById(`day${b}_${f}`).checked?e+\"T\":e+\"F\";f=document.getElementById(`toggle${b}`);var m=document.getElementById(`tseekbar${b}`);if(null==l[0]||null==l[1]){a=null;break a}c.H=parseInt(l[0]);c.M=parseInt(l[1]);c.D=e;c.A=f.checked;c.V=parseInt(m.value);a[String(b)]=c}}null==a?alert(\"Invalid time input for a timing!\"):(b={},b.request=new XMLHttpRequest,\n"
"b.path=\"/T\",b.body=JSON.stringify(a),I(b))}function S(){k=document.getElementById(\"messages\");for(var a=0;10>a;a++){var b=document.createElement(\"tr\");b.innerHTML=`<td style=\"width: 16%; text-align: center\">${a+1}.</td>\n"
"<td style=\"width: 42%; text-align: left\">-</td>\n"
"<td style=\"width: 42%; text-align: left\">-</td>`;k.appendChild(b)}}function T(){n=document.getElementById(\"timings\");for(var a=0;6>a;a++){var b=document.createElement(\"div\");b.style=\"height:30px;\";b.innerHTML=`<p style=\"display:inline-block; padding-left: 2em;\">${a+1}.</p>\n"
"<input id=\"timeSet${a}\" type=\"time\" style=\"display:inline-block; padding-left: 1em;\">\n"
"<input type=\"checkbox\" id=\"day${a}_0\" style=\"display:inline-block; padding-left: 1em;\">\n"
"<label for=\"day${a}_0\">M</label>\n"
"<input type=\"checkbox\" id=\"day${a}_1\" style=\"display:inline-block; padding-left: 1em;\">\n"
"<label for=\"day${a}_1\">Tu</label>\n"
"<input type=\"checkbox\" id=\"day${a}_2\" style=\"display:inline-block; padding-left: 1em;\">\n"
"<label for=\"day${a}_2\">W</label>\n"
"<input type=\"checkbox\" id=\"day${a}_3\" style=\"display:inline-block; padding-left: 1em;\">\n"
"<label for=\"day${a}_3\">Th</label>\n"
"<input type=\"checkbox\" id=\"day${a}_4\" style=\"display:inline-block; padding-left: 1em;\">\n"
"<label for=\"day${a}_4\">F</label>\n"
"<input type=\"checkbox\" id=\"day${a}_5\" style=\"display:inline-block; padding-left: 1em;\">\n"
"<label for=\"day${a}_5\">Sa</label>\n"
"<input type=\"checkbox\" id=\"day${a}_6\" style=\"display:inline-block; padding-left: 1em;\">\n"
"<label for=\"day${a}_6\">Su</label>\n"
"<input type=\"range\" min=\"0\" max=\"100\" name=\"V\" id=\"tseekbar${a}\" value=\"\" style=\"display:inline-block;\">\n"
"<div id=\"seekbarValue${a}\" style=\"display:inline-block\"></div> &nbsp;\n"
"<input type=\"checkbox\" style=\"display:inline-block; padding-left: 1em;\" id=\"toggle${a}\">\n"
"<label for=\"toggle${a}\">Active</label>`;n.appendChild(b)}for(a=0;6>a;a++)b=document.getElementById(`tseekbar${a}`),b.g=document.getElementById(`seekbarValue${a}`),p.push(b),p[a].oninput=function(){this.g.innerText=this.value}}\n"
"function O(a,b,c){if(\"E\"==a)return\"-\";if(\"I\"==a)return\"Server startup.\";if(\"J\"==a)return\"JSON Error: \"+b+\", \"+c;if(\"Z\"==a){if(\"F\"==b)return\"Zeroing failed.\";if(\"O\"==b){if(\"U\"==c)return\"Zeroing: up.\";if(\"D\"==c)return\"Zeroing: down.\"}}if(\"T\"==a)return\"\"+b+\". timing set: \"+c+\"%.\";if(\"S\"==a){if(\"M\"==b)return\"Manual set: \"+c+\"%.\";if(\"Z\"==b)return\"Position found: \"+c+\"%.\";if(\"T\"==b)return\"Timings updated.\"}return\"Unknown event: \"+a+\", \"+b+\", \"+c}\n"
"window.onload=function(){d=document.getElementById(\"curVal\");g=document.getElementById(\"startup\");h=document.getElementById(\"stat\");r=document.getElementById(\"seekbarValue\");q=document.getElementById(\"seekbar\");q.oninput=function(){r.innerText=q.value};x=document.getElementById(\"timingButton\");x.onclick=R;y=document.getElementById(\"setButton\");y.onclick=Q;z=document.getElementById(\"upButton\");z.onclick=J;A=document.getElementById(\"downButton\");A.onclick=K;B=document.getElementById(\"autoButton\");B.onclick=\n"
"L;S();T();E();P();setInterval(function(){if(0==C.length&&1!=v&&null==D&&5>w){var a=M();I(a)}},3E4)};\n"
"</script>\n"
"</head>\n"
"<body>\n"
"<div style=\"display:inline-flex;\">\n"
"<h2 style=\"display:inline-block;\">Shutter Controller!</h2>\n"
"&nbsp; &nbsp;&nbsp; &nbsp;&nbsp; &nbsp;\n"
"<p style=\"display:inline-block;margin-top: 6%;margin-left:3em;\">Hello "USER_NAME"!</p>\n"
"&nbsp; &nbsp;\n"
"<form action=\"./O\">\n"
"<input type=\"submit\" style=\"display:inline-block; margin-top: 40%;\" value=\"Sign out\">\n"
"</form>\n"
"</div>\n"
"\n"
"<div class=\"tab\">\n"
"<button class=\"tablinks\" onclick=\"openTab(event, 'set')\">Set</button>\n"
"<button class=\"tablinks\" onclick=\"openTab(event, 'time')\">Timing</button>\n"
"<button class=\"tablinks\" onclick=\"openTab(event, 'zero')\">Zeroing</button>\n"
"</div>\n"
"\n"
"<div id=\"set\" class=\"tabcontent\">\n"
"<h5 style=\"height:0px;\">Set: </h5>\n"
"<div style=\"display:inline-flex;\">\n"
"<label for=\"fname\">Set:</label><br>\n"
"<input type=\"range\" min=\"0\" max=\"100\" name=\"V\" id=\"seekbar\" value=\"\"><br>\n"
"<div id=\"seekbarValue\"></div> &nbsp;\n"
"<button id=\"setButton\">Send</button>\n"
"</div><br><br>\n"
"<div style=\"display:inline-flex;\">\n"
"<div>Current value: &nbsp;</div>\n"
"<div id=\"curVal\"></div>\n"
"</div><br><br>\n"
"</div>\n"
"\n"
"<div id=\"time\" class=\"tabcontent\">\n"
"<h5 style=\"height:0px;\">Timings: </h5>\n"
"\n"
"<div id=\"timings\">\n"
"\n"
"</div>\n"
"\n"
"<br>\n"
"<br>\n"
"<input type=\"submit\" value=\"Send\" style=\"margin-left: 2em;\" id=\"timingButton\">\n"
"\n"
"</div>\n"
"\n"
"<div id=\"zero\" class=\"tabcontent\">\n"
"<h5 style=\"height: 10px;\">Type of zeroing:</h5>\n"
"<button id=\"upButton\" style=\"margin-left: 2em\">Up</button>\n"
"<button id=\"downButton\" style=\"margin-left: 2em\">Down</button>\n"
"<button id=\"autoButton\" style=\"margin-left: 2em\">Find</button>\n"
"<br>\n"
"</div>\n"
"\n"
"<div style=\"display:inline-flex;width: 100%;\">\n"
"<div style=\"width:40%;\">\n"
"<h5 style=\"height:0px;\">Messages: </h5>\n"
"<table style=\"width: 100%;\" id=\"messages\">\n"
"<tr>\n"
"<th style=\"width: 16%;\">ID</th>\n"
"<th style=\"width: 32%; text-align: left;\">Message</th>\n"
"<th style=\"width: 42%; text-align: left;\">Time</th>\n"
"</tr>\n"
"</table>\n"
"</div>\n"
"\n"
"<div style=\"width:20%;\">\n"
"<br><br>\n"
"<div style=\"display:inline-flex;\">\n"
"<div>State: &nbsp; </div>\n"
"<div id=\"stat\"></div>\n"
"</div><br><br>\n"
"\n"
"<div style=\"display:inline-flex;\">\n"
"<div>Startup: &nbsp; </div>\n"
"<div id=\"startup\"></div>\n"
"</div><br><br>\n"
"</div>\n"
"\n"
"</div>\n"
"<br>\n"
"\n"
"<script>\n"
"function openTab(evt, cityName) {\n"
"var i, tabcontent, tablinks;\n"
"tabcontent = document.getElementsByClassName(\"tabcontent\");\n"
"for (i = 0; i < tabcontent.length; i++) {\n"
"tabcontent[i].style.display = \"none\";\n"
"}\n"
"tablinks = document.getElementsByClassName(\"tablinks\");\n"
"for (i = 0; i < tablinks.length; i++) {\n"
"tablinks[i].className = tablinks[i].className.replace(\" active\", \"\");\n"
"}\n"
"document.getElementById(cityName).style.display = \"block\";\n"
"evt.currentTarget.className += \" active\";\n"
"}\n"
"</script>\n"
"</body>\n"
"</html>\n";

#endif