#ifndef BROWSERCLIENT_H
#define BROWSERCLIENT_H

namespace StaticPage {
    const char protoFormat[] PROGMEM = "syntax = \"proto3\";\n"
    "\n"
    "package Shutter;\n"
    "\n"
    "enum Event {\n"
    "    empty = 0;\n"
    "    start = 1;\n"
    "    set = 2;\n"
    "    timing = 3;\n"
    "    zero = 4;\n"
    "    zero_fail = 5;\n"
    "    zero_find = 6;\n"
    "    timings_updated = 7;\n"
    "}\n"
    "\n"
    "enum Zero {\n"
    "    current = 0;\n"
    "    up = 1;\n"
    "    down = 2;\n"
    "}\n"
    "\n"
    "message Timing {\n"
    "    int32 value = 1;\n"
    "\n"
    "    int32 hour = 2;\n"
    "    int32 minute = 3;\n"
    "    \n"
    "    repeated bool days = 4;\n"
    "    bool active = 5;\n"
    "}\n"
    "\n"
    "message TimingContainer {\n"
    "    repeated Timing timing = 1;\n"
    "}\n"
    "\n"
    "message GenericMessage {\n"
    "    int32 value = 1;\n"
    "    Event event = 2;\n"
    "    string datetime = 3;\n"
    "}\n"
    "\n"
    "message MessageContainer {\n"
    "    repeated GenericMessage genericMessage = 1;\n"
    "    string startTime = 2;\n"
    "}\n"
    "\n"
    "message Response{\n"
    "    int32 value = 1;\n"
    "    int32 retryTime = 2;\n"
    "    MessageContainer messageContainer = 3;\n"
    "}\n"
    "\n"
    "message Request {\n"
    "    repeated Timing timing = 1;\n"
    "    int32 value = 2;\n"
    "    Zero zero = 3;\n"
    "}\n"
    "\n"
    "message CurrentState {\n"
    "    float value = 1;\n"
    "    int32 day = 2;\n"
    "    int32 hour = 3;\n"
    "    int32 minute = 4;\n"
    "}\n";

    //The sign-in page
    const char loginPage[] PROGMEM = "<!DOCTYPE html>\n"
    "<html lang=\"en\" data-bs-theme=\"light\"><head>\n"
    "<meta http-equiv=\"content-type\" content=\"text/html; charset=UTF-8\">\n"
    "<meta charset=\"utf-8\">\n"
    "<meta name=\"viewport\" content=\"width=device-width, initial-scale=1\">\n"
    "<meta name=\"description\" content=\"\">\n"
    "<meta name=\"author\" content=\"Péter Máté Margitai\">\n"
    "<title>Shutter Controller - login failed</title>\n"
    "<link href=\"https://cdn.jsdelivr.net/npm/bootstrap@5.3.2/dist/css/bootstrap.min.css\" rel=\"stylesheet\" integrity=\"sha384-T3c6CoIi6uLrA9TneNEoa7RxnatzjcDSCmG1MXxSR1GAsXEV/Dwwykc2MPK8M2HN\" crossorigin=\"anonymous\">\n"
    "<script src=\"https://cdn.jsdelivr.net/npm/bootstrap@5.3.2/dist/js/bootstrap.bundle.min.js\" integrity=\"sha384-C6RzsynM9kWDrMNeT87bh95OGNyZPhcTNXj1NW7RuBCsyN/o0jlpcV8Qyq46cDfL\" crossorigin=\"anonymous\"></script>\n"
    "<link rel=\"stylesheet\" href=\"https://cdn.jsdelivr.net/npm/@docsearch/css@3\">\n"
    "</head>\n"
    "<body>\n"
    "<main class=\"container\">\n"
    "<header class=\"py-3 mb-4 border-bottom\">\n"
    "<div class=\"d-flex flex-wrap justify-content-between\">\n"
    "<a href=\"/\" class=\"d-flex align-items-center mb-3 mb-md-0 me-md-auto link-body-emphasis text-decoration-none\">\n"
    "<span class=\"fs-4\">Shutter Controller</span>\n"
    "</a>\n"
    "</div>\n"
    "</header>\n"
    "<div class=\"form-signin w-100 m-auto d-flex justify-content-center\">\n"
    "<form class=\"col-8 col-md-6\" method=\"POST\" action=\"./L\">\n"
    "<h1 class=\"h3 mb-3 fw-normal\">Sign in</h1> \n"
    "<div class=\"form-floating\">\n"
    "<input type=\"text\" class=\"form-control\" id=\"floatingInput\" placeholder=\"username\" name=\"username\" style=\"cursor: auto;\">\n"
    "<label for=\"floatingInput\">Username</label>\n"
    "</div>\n"
    "<div class=\"form-floating\">\n"
    "<input type=\"password\" class=\"form-control\" id=\"floatingPassword\" placeholder=\"Password\" name=\"password\" style=\"cursor: auto;\">\n"
    "<label for=\"floatingPassword\">Password</label>\n"
    "</div>\n"
    "<button class=\"btn btn-primary w-100 py-2 col-6 form-group\" type=\"submit\">Sign in</button>\n"
    "</form>\n"
    "</div>\n"
    "</main>\n"
    "</body>\n"
    "</html>";

    //page showed when bad credentials were given
    const char loginFail[] PROGMEM = "<!DOCTYPE html>\n"
    "<html lang=\"en\" data-bs-theme=\"light\"><head>\n"
    "<meta http-equiv=\"content-type\" content=\"text/html; charset=UTF-8\">\n"
    "<meta charset=\"utf-8\">\n"
    "<meta name=\"viewport\" content=\"width=device-width, initial-scale=1\">\n"
    "<meta name=\"description\" content=\"\">\n"
    "<meta name=\"author\" content=\"Péter Máté Margitai\">\n"
    "<title>Shutter Controller - login failed</title>\n"
    "<link href=\"https://cdn.jsdelivr.net/npm/bootstrap@5.3.2/dist/css/bootstrap.min.css\" rel=\"stylesheet\" integrity=\"sha384-T3c6CoIi6uLrA9TneNEoa7RxnatzjcDSCmG1MXxSR1GAsXEV/Dwwykc2MPK8M2HN\" crossorigin=\"anonymous\">\n"
    "<script src=\"https://cdn.jsdelivr.net/npm/bootstrap@5.3.2/dist/js/bootstrap.bundle.min.js\" integrity=\"sha384-C6RzsynM9kWDrMNeT87bh95OGNyZPhcTNXj1NW7RuBCsyN/o0jlpcV8Qyq46cDfL\" crossorigin=\"anonymous\"></script>\n"
    "<link rel=\"stylesheet\" href=\"https://cdn.jsdelivr.net/npm/@docsearch/css@3\">\n"
    "</head>\n"
    "<body>\n"
    "<main class=\"container\">\n"
    "<header class=\"py-3 mb-4 border-bottom\">\n"
    "<div class=\"d-flex flex-wrap justify-content-between\">\n"
    "<a href=\"/\" class=\"d-flex align-items-center mb-3 mb-md-0 me-md-auto link-body-emphasis text-decoration-none\">\n"
    "<span class=\"fs-4\">Shutter Controller</span>\n"
    "</a>\n"
    "</div>\n"
    "</header>\n"
    "<div class=\"d-flex justify-content-center\">\n"
    "<h2>Login failed, invalid credentials!</h2>\n"
    "</div>\n"
    "</main>\n"
    "</body>\n"
    "</html>";

    //the main page controlling the shutter
    const char controlPage[] PROGMEM = "<!DOCTYPE html>\n"
    "<html lang=\"en\" data-bs-theme=\"light\"><head>\n"
    "<meta http-equiv=\"content-type\" content=\"text/html; charset=UTF-8\">\n"
    "<meta charset=\"utf-8\">\n"
    "<meta name=\"viewport\" content=\"width=device-width, initial-scale=1\">\n"
    "<meta name=\"description\" content=\"\">\n"
    "<meta name=\"author\" content=\"Péter Máté Margitai\">\n"
    "<title>Shutter Controller</title>\n"
    "<link href=\"https://cdn.jsdelivr.net/npm/bootstrap@5.3.2/dist/css/bootstrap.min.css\" rel=\"stylesheet\" integrity=\"sha384-T3c6CoIi6uLrA9TneNEoa7RxnatzjcDSCmG1MXxSR1GAsXEV/Dwwykc2MPK8M2HN\" crossorigin=\"anonymous\">\n"
    "<script src=\"https://cdn.jsdelivr.net/npm/bootstrap@5.3.2/dist/js/bootstrap.bundle.min.js\" integrity=\"sha384-C6RzsynM9kWDrMNeT87bh95OGNyZPhcTNXj1NW7RuBCsyN/o0jlpcV8Qyq46cDfL\" crossorigin=\"anonymous\"></script>\n"
    "<link rel=\"stylesheet\" href=\"https://cdn.jsdelivr.net/npm/@docsearch/css@3\">\n"
    "<script src=\"//cdn.jsdelivr.net/npm/protobufjs@7.2.6/dist/protobuf.js\"></script>\n"
    "<script src=\"https://cdnjs.cloudflare.com/ajax/libs/sprintf/1.1.3/sprintf.min.js\"></script>\n"
    "<script type=\"module\" src=\"" RESOURCE_PROVIDER "/control.js?testMode=false\" id=\"control\"></script>\n"
    "</head>\n"
    "<body>\n"
    "<main class=\"container\">\n"
    "<header class=\"py-3 mb-4 border-bottom\">\n"
    "<div class=\"d-flex flex-wrap justify-content-between\">\n"
    "<a href=\"/\" class=\"d-flex align-items-center mb-3 mb-md-0 me-md-auto link-body-emphasis text-decoration-none\">\n"
    "<span class=\"fs-4\">Shutter Controller</span>\n"
    "</a>\n"
    "<div class=\"d-flex dropdown text-end align-items-center\">\n"
    "<a class=\"d-block link-body-emphasis text-decoration-none dropdown-toggle\" data-bs-toggle=\"dropdown\" aria-expanded=\"false\" href=\"#\">\n"
    USER_NAME
    "</a>\n"
    "<ul class=\"dropdown-menu text-small\">\n"
    "<li><a class=\"dropdown-item\" href=\"/W\">WASM-client</a></li>\n"
    "<li><hr class=\"dropdown-divider\"></li>\n"
    "<li><a class=\"dropdown-item\" href=\"/O\">Sign out</a></li>\n"
    "</ul>\n"
    "</div>\n"
    "</div>\n"
    "</header>\n"
    "<div class=\"container-fluid\">\n"
    "<div class=\"row\">\n"
    "<div class=\"col-8 mx-auto\">\n"
    "<ul class=\"nav nav-underline justify-content-center\">\n"
    "<li class=\"nav-item col-3 d-flex justify-content-center\">\n"
    "<a class=\"nav-link active\" data-bs-toggle=\"tab\" href=\"#setting\">Setting</a>\n"
    "</li>\n"
    "<li class=\"nav-item col-3 d-flex justify-content-center\">\n"
    "<a class=\"nav-link\" data-bs-toggle=\"tab\" href=\"#timing\">Timing</a>\n"
    "</li>\n"
    "<li class=\"nav-item col-3 d-flex justify-content-center\">\n"
    "<a class=\"nav-link\" data-bs-toggle=\"tab\" href=\"#zeroing\">Zeroing</a>\n"
    "</li>\n"
    "</ul>\n"
    "</div>\n"
    "</div>\n"
    "</div>\n"
    "<div class=\"tab-content mt-4\">\n"
    "<div class=\"tab-pane container active\" id=\"setting\">\n"
    "<div class=\"row justify-content-center align-items-center\">\n"
    "<div class=\"col-12 col-md-6 pt-2 pb-2 border\">\n"
    "<div class=\"row d-flex align-items-center justify-content-between\">\n"
    "<div class=\"col-2\">\n"
    "<label for=\"seekbar\">Position:</label>\n"
    "</div>\n"
    "<div class=\"col-6 d-flex align-items-center\">\n"
    "<input type=\"range\" id=\"seekbar\" name=\"seekbar\" class=\"form-range\" step=\"5\" min=\"0\" max=\"100\">\n"
    "</div>\n"
    "<div class=\"col-1\">\n"
    "<span class=\"range-value\" id=\"seekbarValueText\">0%</span>\n"
    "</div>\n"
    "<div class=\"col-2\">\n"
    "<button type=\"button\" class=\"btn btn-primary btn-sm\" id=\"setButton\">Set</button>\n"
    "</div>\n"
    "</div>\n"
    "</div>\n"
    "</div>\n"
    "</div>\n"
    "<div class=\"tab-pane container fade\" id=\"timing\">\n"
    "<div class=\"row justify-content-center align-items-center\">\n"
    "<div class=\"col-12 col-md-6\">\n"
    "<div id=\"timings\">\n"
    "<template id=\"timingTemplate\">\n"
    "<div class=\"container mb-2 pb-2 pt-2 border\">\n"
    "<div class=\"row d-flex align-items-center\">\n"
    "<h5 class=\"col-1 d-flex align-items-center\" id=\"timingId\">-</h5>\n"
    "<div class=\"col-5 col-md-3\">\n"
    "<input class=\"form-control text-center col-1\" type=\"time\" id=\"timeSet\">\n"
    "</div>\n"
    "<div class=\"form-check col-4 col-md-2\">\n"
    "<label class=\"form-check-label\" for=\"flexCheckDefault\">active</label>\n"
    "<input class=\"form-check-input\" type=\"checkbox\" value=\"\" id=\"activeCheck\">\n"
    "</div>\n"
    "</div>\n"
    "<div class=\"row ms-3\" id=\"daySelector\"></div>\n"
    "<div class=\"row ms-1\">\n"
    "<div class=\"col-3 col-md-2\">\n"
    "<label for=\"seekbar\">Position:</label>\n"
    "</div>\n"
    "<div class=\"col-6 d-flex align-items-center\">\n"
    "<input type=\"range\" id=\"seekbar\" name=\"seekbar\" class=\"form-range\" step=\"5\" min=\"0\" max=\"100\">\n"
    "</div>\n"
    "<div class=\"col-1\">\n"
    "<span class=\"range-value\" id=\"seekbarValueText\">0%</span>\n"
    "</div>\n"
    "</div>\n"
    "</div>\n"
    "</template>\n"
    "<template id=\"checkboxTemplate\">\n"
    "<div class=\"form-check col-3\">\n"
    "<label class=\"form-check-label\" for=\"flexCheckDefault\" id=\"dayLabel\">-</label>\n"
    "<input class=\"form-check-input day-check\" type=\"checkbox\" value=\"\" id=\"dayCheck\">\n"
    "</div>\n"
    "</template>\n"
    "</div>\n"
    "<div class=\"row justify-content-center\">\n"
    "<div class=\"col-2\">\n"
    "<button type=\"button\" class=\"btn btn-primary\" id=\"timingButton\">Set</button>\n"
    "</div>\n"
    "</div>\n"
    "</div>\n"
    "</div>\n"
    "</div>\n"
    "<div class=\"tab-pane container fade\" id=\"zeroing\">\n"
    "<div class=\"row justify-content-center align-items-center\">\n"
    "<div class=\"col-12 col-md-6 pt-2 pb-2 border\">\n"
    "<div class=\"row d-flex align-items-center justify-content-between\">\n"
    "<div class=\"col-3 d-flex justify-content-center\">\n"
    "<button type=\"button\" class=\"btn btn-primary\" id=\"upButton\">Up</button>\n"
    "</div>\n"
    "<div class=\"col-3 d-flex justify-content-center\">\n"
    "<button type=\"button\" class=\"btn btn-primary\" id=\"downButton\">Down</button>\n"
    "</div>\n"
    "<div class=\"col-3 d-flex justify-content-center\">\n"
    "<button type=\"button\" class=\"btn btn-primary\" id=\"autoButton\">Find</button>\n"
    "</div>\n"
    "</div>\n"
    "</div>\n"
    "</div>\n"
    "</div>\n"
    "</div>\n"
    "<div class=\"container-fluid mt-3\">\n"
    "<div class=\"row\">\n"
    "<div class=\"col-md-6 col-12 mx-auto\">\n"
    "<div class=\"row\">\n"
    "<p class=\"col-md-3 col-4\">Current position: </p>\n"
    "<p class=\"col-md-2 col-2\" id=\"curVal\"></p>\n"
    "</div>\n"
    "<div class=\"row\">\n"
    "<p class=\"col-md-3 col-4\">Server state: </p>\n"
    "<p class=\"col-8\" id=\"stat\"></p>\n"
    "</div>\n"
    "<div class=\"row\">\n"
    "<p class=\"col-md-3 col-4\">Server start time: </p>\n"
    "<p class=\"col-6\" id=\"startup\"></p>\n"
    "</div>\n"
    "</div>\n"
    "</div>\n"
    "</div>\n"
    "<div class=\"container-fluid mt-3\">\n"
    "<div class=\"row\">\n"
    "<div class=\"col-md-6 col-12 mx-auto\">\n"
    "<table class=\"table\">\n"
    "<thead>\n"
    "<tr>\n"
    "<th scope=\"col\">ID</th>\n"
    "<th scope=\"col\">Event</th>\n"
    "<th scope=\"col\">Date</th>\n"
    "</tr>\n"
    "</thead>\n"
    "<tbody id=\"messages\">\n"
    "<template id=\"messageTemplate\">\n"
    "<tr>\n"
    "<th scope=\"row\" id=\"id\">1</th>\n"
    "<td id=\"event\"></td>\n"
    "<td id=\"date\"></td>\n"
    "</tr>\n"
    "</template>\n"
    "</tbody>\n"
    "</table>\n"
    "</div>\n"
    "</div>\n"
    "</div>\n"
    "</main>\n"
    "</body>\n"
    "</html>";

    //the page containing the wasm module
    const char wasmPage[] PROGMEM = "<!DOCTYPE html>\n"
    "<html lang=\"en\" data-bs-theme=\"light\"><head>\n"
    "<meta http-equiv=\"content-type\" content=\"text/html; charset=UTF-8\">\n"
    "<meta charset=\"utf-8\">\n"
    "<meta name=\"viewport\" content=\"width=device-width, initial-scale=1\">\n"
    "<meta name=\"description\" content=\"\">\n"
    "<meta name=\"author\" content=\"Péter Máté Margitai\">\n"
    "<title>Shutter Controller - WASM-client</title>\n"
    "<link href=\"https://cdn.jsdelivr.net/npm/bootstrap@5.3.2/dist/css/bootstrap.min.css\" rel=\"stylesheet\" integrity=\"sha384-T3c6CoIi6uLrA9TneNEoa7RxnatzjcDSCmG1MXxSR1GAsXEV/Dwwykc2MPK8M2HN\" crossorigin=\"anonymous\">\n"
    "<script src=\"https://cdn.jsdelivr.net/npm/bootstrap@5.3.2/dist/js/bootstrap.bundle.min.js\" integrity=\"sha384-C6RzsynM9kWDrMNeT87bh95OGNyZPhcTNXj1NW7RuBCsyN/o0jlpcV8Qyq46cDfL\" crossorigin=\"anonymous\"></script>\n"
    "<link rel=\"stylesheet\" href=\"https://cdn.jsdelivr.net/npm/@docsearch/css@3\">\n"
    "</head>\n"
    "<body>\n"
    "<main class=\"container\">\n"
    "<header class=\"py-3 mb-4 border-bottom\">\n"
    "<div class=\"d-flex flex-wrap justify-content-between\">\n"
    "<a href=\"/\" class=\"d-flex align-items-center mb-3 mb-md-0 me-md-auto link-body-emphasis text-decoration-none\">\n"
    "<span class=\"fs-4\">Shutter Controller</span>\n"
    "</a>\n"
    "<div class=\"d-flex dropdown text-end align-items-center\">\n"
    "<a class=\"d-block link-body-emphasis text-decoration-none dropdown-toggle\" data-bs-toggle=\"dropdown\" aria-expanded=\"false\" href=\"#\">\n"
    USER_NAME
    "</a>\n"
    "<ul class=\"dropdown-menu text-small\">\n"
    "<li><a class=\"dropdown-item\" href=\"/\">HTML-client</a></li>\n"
    "<li><hr class=\"dropdown-divider\"></li>\n"
    "<li><a class=\"dropdown-item\" href=\"/O\">Sign out</a></li>\n"
    "</ul>\n"
    "</div>\n"
    "</div>\n"
    "</header>\n"
    "<div class=\"container d-flex justify-content-center\">\n"
    "<canvas id=\"canvas\" class=\"emscripten col-12 col-md-4 mh-100\" style=\"height: 600px\" oncontextmenu=\"event.preventDefault()\" tabindex=-1>Canvas for WASM.</canvas>\n"
    "</div>\n"
    "<script type='text/javascript'>\n"
    "var Module = {\n"
    "canvas: (function() { return document.getElementById('canvas'); })(),\n"
    "demoMode: false\n"
    "};\n"
    "</script>\n"
    "<script async type=\"text/javascript\" src=\"" RESOURCE_PROVIDER "/ShutterClient.js\" ></script>\n"
    "</main>\n"
    "</body>\n"
    "</html>";

    //worker/thread module for the wasm module, TODO:should be served from an external server
    const char wasmWorker[] PROGMEM = "\"use strict\";var Module={};var ENVIRONMENT_IS_NODE=typeof process==\"object\"&&typeof process.versions==\"object\"&&typeof process.versions.node==\"string\";if(ENVIRONMENT_IS_NODE){var nodeWorkerThreads=require(\"worker_threads\");var parentPort=nodeWorkerThreads.parentPort;parentPort.on(\"message\",data=>onmessage({data:data}));var fs=require(\"fs\");var vm=require(\"vm\");Object.assign(global,{self:global,require:require,Module:Module,location:{href:__filename},Worker:nodeWorkerThreads.Worker,importScripts:f=>vm.runInThisContext(fs.readFileSync(f,\"utf8\"),{filename:f}),postMessage:msg=>parentPort.postMessage(msg),performance:global.performance||{now:Date.now}})}var initializedJS=false;function threadPrintErr(...args){var text=args.join(\" \");if(ENVIRONMENT_IS_NODE){fs.writeSync(2,text+\"\\n\");return}console.error(text)}function threadAlert(...args){var text=args.join(\" \");postMessage({cmd:\"alert\",text:text,threadId:Module[\"_pthread_self\"]()})}var err=threadPrintErr;self.alert=threadAlert;Module[\"instantiateWasm\"]=(info,receiveInstance)=>{var module=Module[\"wasmModule\"];Module[\"wasmModule\"]=null;var instance=new WebAssembly.Instance(module,info);return receiveInstance(instance)};self.onunhandledrejection=e=>{throw e.reason||e};function handleMessage(e){try{if(e.data.cmd===\"load\"){let messageQueue=[];self.onmessage=e=>messageQueue.push(e);self.startWorker=instance=>{postMessage({\"cmd\":\"loaded\"});for(let msg of messageQueue){handleMessage(msg)}self.onmessage=handleMessage};Module[\"wasmModule\"]=e.data.wasmModule;for(const handler of e.data.handlers){Module[handler]=(...args)=>{postMessage({cmd:\"callHandler\",handler:handler,args:args})}}Module[\"wasmMemory\"]=e.data.wasmMemory;Module[\"buffer\"]=Module[\"wasmMemory\"].buffer;Module[\"ENVIRONMENT_IS_PTHREAD\"]=true;if(typeof e.data.urlOrBlob==\"string\"){importScripts(e.data.urlOrBlob)}else{var objectUrl=URL.createObjectURL(e.data.urlOrBlob);importScripts(objectUrl);URL.revokeObjectURL(objectUrl)}}else if(e.data.cmd===\"run\"){Module[\"__emscripten_thread_init\"](e.data.pthread_ptr,0,0,1);Module[\"__emscripten_thread_mailbox_await\"](e.data.pthread_ptr);Module[\"establishStackSpace\"]();Module[\"PThread\"].receiveObjectTransfer(e.data);Module[\"PThread\"].threadInitTLS();if(!initializedJS){Module[\"__embind_initialize_bindings\"]();initializedJS=true}try{Module[\"invokeEntryPoint\"](e.data.start_routine,e.data.arg)}catch(ex){if(ex!=\"unwind\"){throw ex}}}else if(e.data.cmd===\"cancel\"){if(Module[\"_pthread_self\"]()){Module[\"__emscripten_thread_exit\"](-1)}}else if(e.data.target===\"setimmediate\"){}else if(e.data.cmd===\"checkMailbox\"){if(initializedJS){Module[\"checkMailbox\"]()}}else if(e.data.cmd){err(`worker.js received unknown command ${e.data.cmd}`);err(e.data)}}catch(ex){Module[\"__emscripten_thread_crashed\"]?.();throw ex}}self.onmessage=handleMessage;";
}

#endif
